ARG BASE_IMAGE=ubuntu:24.04
FROM ${BASE_IMAGE}

LABEL maintainer="IRSL-tut (https://github.com/IRSL-tut) <faculty@irsl.eiiris.tut.ac.jp>"

RUN mkdir -p /ros_home/log && chmod a+rwx /ros_home && chmod a+rwx /ros_home/log

RUN echo -e '#!/bin/bash\n\
set -e\n\
source /irsl_entryrc\n\
exec "$@"\n' >> /irsl_entrypoint.sh

RUN chmod a+x /irsl_entrypoint.sh

RUN <<EOF
cat - << _DOC_ >> /irsl_entryrc
# setup ros environment
if [ -e "\${DOCKER_ROS_SETUP}" ]; then
    source "\${DOCKER_ROS_SETUP}"
else
    source "/opt/ros/\$ROS_DISTRO/setup.bash"
fi
MY_IP=\${DOCKER_ROS_IP:-\$(hostname -i)}
if [ "\$ROS_IP" == "" ]; then
    export ROS_IP=\${MY_IP}
fi
if [ "\$ROS_HOSTNAME" == "" ]; then
    export ROS_HOSTNAME=\${ROS_IP}
fi
if [ "\${DOCKER_ROS_MASTER_URI}" != "" ]; then
    export ROS_MASTER_URI=\${DOCKER_ROS_MASTER_URI}
fi
if [ -n "\${IRSL_EXTRA_PATH}" ]; then
    export PATH=\$PATH:\${IRSL_EXTRA_PATH}
fi
if [ -n "\${IRSL_EXTRA_LIB}" ]; then
    export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:\${IRSL_EXTRA_LIB}
fi
if [ -n "\${IRSL_ADD_SOURCE}" ]; then
    if [ -e "\${IRSL_ADD_SOURCE}" ]; then
        source "\${IRSL_ADD_SOURCE}"
    fi
fi
export HOME=/ros_home
export ROS_HOME=/ros_home

## activate virtual env
if [ -e /irsl_venv/bin/activate ]; then
    source /irsl_venv/bin/activate
fi
_DOC_
EOF

ENTRYPOINT ["/irsl_entrypoint.sh"]
